
@main
def run(): Unit =
  // day1.solution("data/day1/input.txt").run()
  // day2.solution("data/day2/input.txt").run()
  // day3.solution("data/day3/input.txt").run()
  // day4.solution("data/day4/input.txt").run()
  // day5.solution("data/day5/input.txt").run()
  // day6.solution("data/day6/input.txt").run()
  // day7.solution("data/day7/input.txt").run()
  // day8.solution("data/day8/input.txt").run()
  // day9.solution("data/day9/input.txt").run()
  // day10.solution("data/day10/input.txt").run()
  // day11.solution("data/day11/input.txt").run()
  // day12.solution("data/day12/input.txt").run()
  // day13.solution("data/day13/input.txt").run()
  // day14.solution("data/day14/input.txt").run()
  // day15.solution("data/day15/input.txt").run()
  // day16.solution("data/day16/input.txt").run()
  // day17.solution("data/day17/input.txt").run()
  // day18.solution("data/day18/input.txt").run()
  // day19.solution("data/day19/input.txt").run()
  // day20.solution("data/day20/input.txt").run()
  // day21.solution("data/day21/input.txt").run()
  day22.solution("data/day22/input.txt").run()

